/home2/txlx81/new_repos/mv_test1/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home2/txlx81/new_repos/mv_test1/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home2/txlx81/test-repos/ood_art_tests/sampler_utils.py:142: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  confidence = torch.tensor(results).max(dim=1).values
Using cache found in /home2/txlx81/.cache/torch/hub/pytorch_vision_v0.10.0
wandb: Currently logged in as: mridulav. Use `wandb login --relogin` to force relogin
wandb: - Waiting for wandb.init()...wandb: \ Waiting for wandb.init()...wandb: | Waiting for wandb.init()...Thread HandlerThread:
Traceback (most recent call last):
  File "/home2/txlx81/new_repos/mv_test1/lib/python3.8/site-packages/wandb/sdk/internal/internal_util.py", line 49, in run
    self._run()
  File "/home2/txlx81/new_repos/mv_test1/lib/python3.8/site-packages/wandb/sdk/internal/internal_util.py", line 100, in _run
    self._process(record)
  File "/home2/txlx81/new_repos/mv_test1/lib/python3.8/site-packages/wandb/sdk/internal/internal.py", line 279, in _process
    self._hm.handle(record)
  File "/home2/txlx81/new_repos/mv_test1/lib/python3.8/site-packages/wandb/sdk/internal/handler.py", line 136, in handle
    handler(record)
  File "/home2/txlx81/new_repos/mv_test1/lib/python3.8/site-packages/wandb/sdk/internal/handler.py", line 146, in handle_request
    handler(record)
  File "/home2/txlx81/new_repos/mv_test1/lib/python3.8/site-packages/wandb/sdk/internal/handler.py", line 696, in handle_request_run_start
    self._tb_watcher = tb_watcher.TBWatcher(
  File "/home2/txlx81/new_repos/mv_test1/lib/python3.8/site-packages/wandb/sdk/internal/tb_watcher.py", line 118, in __init__
    wandb.tensorboard.reset_state()
  File "/home2/txlx81/new_repos/mv_test1/lib/python3.8/site-packages/wandb/sdk/lib/lazyloader.py", line 58, in __getattr__
    module = self._load()
  File "/home2/txlx81/new_repos/mv_test1/lib/python3.8/site-packages/wandb/sdk/lib/lazyloader.py", line 33, in _load
    module = importlib.import_module(self.__name__)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home2/txlx81/new_repos/mv_test1/lib/python3.8/site-packages/wandb/integration/tensorboard/__init__.py", line 3, in <module>
    from .log import _log, log, reset_state, tf_summary_to_dict  # noqa: F401
  File "/home2/txlx81/new_repos/mv_test1/lib/python3.8/site-packages/wandb/integration/tensorboard/log.py", line 35, in <module>
    Summary = pb.Summary if pb else None
  File "/usr/lib/python3.8/importlib/util.py", line 245, in __getattribute__
    self.__spec__.loader.exec_module(self)
  File "/home2/txlx81/new_repos/mv_test1/lib/python3.8/site-packages/tensorboard/compat/proto/summary_pb2.py", line 17, in <module>
    from tensorboard.compat.proto import tensor_pb2 as tensorboard_dot_compat_dot_proto_dot_tensor__pb2
  File "/home2/txlx81/new_repos/mv_test1/lib/python3.8/site-packages/tensorboard/compat/proto/tensor_pb2.py", line 16, in <module>
    from tensorboard.compat.proto import resource_handle_pb2 as tensorboard_dot_compat_dot_proto_dot_resource__handle__pb2
  File "/home2/txlx81/new_repos/mv_test1/lib/python3.8/site-packages/tensorboard/compat/proto/resource_handle_pb2.py", line 16, in <module>
    from tensorboard.compat.proto import tensor_shape_pb2 as tensorboard_dot_compat_dot_proto_dot_tensor__shape__pb2
  File "/home2/txlx81/new_repos/mv_test1/lib/python3.8/site-packages/tensorboard/compat/proto/tensor_shape_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "/home2/txlx81/new_repos/mv_test1/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 561, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
wandb: ERROR Internal wandb error: file data was not synced
wandb: ERROR transport failed
Traceback (most recent call last):
  File "main.py", line 93, in <module>
    wandb.init(project='ood_art_tests_v2',
  File "/home2/txlx81/new_repos/mv_test1/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1169, in init
    raise e
  File "/home2/txlx81/new_repos/mv_test1/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1150, in init
    run = wi.init()
  File "/home2/txlx81/new_repos/mv_test1/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 799, in init
    run_start_result = run_start_handle.wait(timeout=30)
  File "/home2/txlx81/new_repos/mv_test1/lib/python3.8/site-packages/wandb/sdk/lib/mailbox.py", line 281, in wait
    raise MailboxError("transport failed")
wandb.sdk.lib.mailbox.MailboxError: transport failed
wandb: While tearing down the service manager. The following error has occurred: [Errno 32] Broken pipe
